# standard configuration:
runtime: python27
api_version: 1
threadsafe: yes

# Each handler redirects a set of URLs to be handled by a specific file or a script:
handlers:
- url: /logevent # this will redirect requests made to the logging logic
  script: jslogging.app # this will use the script in main.py

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /yanas/
  static_dir: static/yanas/


- url: .* # this will redirect all URLs not handled by anything else above it.
  static_dir: static/

# this specifies what libraries we are using in our App Engine app:
libraries:
- name: flask
  version: "0.12"
